resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: airflow
  spec:
    syncPolicy:
      automated:
        $patch: delete

