resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: airflow-airflow-ingress
  spec:
    rules:
    - host: airflow-prod.dxone.com
      http:
        paths:
        - backend:
            service:
              name: airflow-webserver
              port:
                name: airflow-ui
          path: /
          pathType: Prefix
  ---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: airflow-flower-ingress
  spec:
    rules:
    - host: airflow-prod-flower.dxone.com
      http:
        paths:
        - backend:
            service:
              name: airflow-flower
              port:
                name: flower-ui
          path: /
          pathType: Prefix

