namespace: airflow
helmCharts:
- name: airflow
  valuesFile: values.yaml
  includeCRDs: false
  releaseName: airflow
  version: 1.5.0
  repo: https://airflow.apache.org

patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
      $patch: replace
    name: airflow-create-user
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
      $patch: replace
    name: airflow-run-airflow-migrations

